In [1]:
import pandas as pd

In [5]:
df = pd.read_parquet("dataset_entrenamiento.parquet")

In [13]:
df_clima = pd.read_csv("export (5).csv")
df_clima["date"] = pd.to_datetime(df_clima["date"] )
df_clima = df_clima[["date", "tavg", "prcp", "wspd"]]
df_clima.head()

        date  tavg  prcp  wspd
0 2024-01-01  25.2   2.2   9.5
1 2024-01-02  24.9   0.0   9.7
2 2024-01-03  24.2   9.9  11.6
3 2024-01-04  25.2   0.0  11.8
4 2024-01-05  21.2   3.0  11.4

In [15]:
df = df[["fecha_origen_recorrido", "estacion_origen", "estacion_destino", "grupo_edad", "date_key", "iso_day_of_week", "month_of_year", "day_of_month", "year_key"]]

In [16]:
df

,fecha_origen_recorrido,estacion_origen,estacion_destino,grupo_edad,date_key,iso_day_of_week,month_of_year,day_of_month,year_key
0,2024-10-20 21:34:30,045 - Uruguay,045 - Uruguay,36-45,2024-10-20,7,10,20,2024
1,2024-10-20 20:52:09,293 - GREGORIO DE LAFERRERE,293 - GREGORIO DE LAFERRERE,26-35,2024-10-20,7,10,20,2024
2,2024-10-20 19:22:25,271 - VILLA SOLDATI II,271 - VILLA SOLDATI II,19-25,2024-10-20,7,10,20,2024
3,2024-10-20 18:48:20,145 - RAVIGNANI,145 - RAVIGNANI,19-25,2024-10-20,7,10,20,2024
4,2024-10-20 18:43:48,117 - HUMBERTO 1°,117 - HUMBERTO 1°,36-45,2024-10-20,7,10,20,2024
...,...,...,...,...,...,...,...,...,...
3553068,2024-01-26 16:49:19,146 - Hospital Francés,021 - Parque Patricios,None,2024-01-26,5,1,26,2024
3553069,2024-01-26 20:07:28,265 - Plaza Exodo Jujeño,395 - Agronomia II,None,2024-01-26,5,1,26,2024
3553070,2024-01-26 19:30:17,129 - Velasco,069 - Ecuador,None,2024-01-26,5,1,26,2024
3553071,2024-01-26 19:11:17,047 - PARQUE DE LA INNOVACIÓN,292 - PLAZA BOLIVIA,None,2024-01-26,5,1,26,2024
3553072,2024-01-26 10:20:58,215 - HOSPITAL ALVAREZ,270 - PLAZA DEL ANGEL GRIS,None,2024-01-26,5,1,26,2024

In [17]:
dataset_general = df.merge(df_clima, left_on="date_key", right_on="date", how="left")

In [19]:
dataset_general = dataset_general[["year_key", "month_of_year", "day_of_month" , "iso_day_of_week", "estacion_origen", "estacion_destino", "grupo_edad", "tavg", "prcp", "wspd"]]

In [21]:
dataset_general.to_parquet("dataset_general.parquet")

In [ ]:
df =